accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("ver-req/<email>/", views.verification_required),
    path("activate/<uidb64>/<token>/", views.activate)

]

fakeinsta/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import home_view
from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),
    path("posts/", include(("posts.urls", "posts"), namespace="posts")),
    path('', home_view)
    ] 


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]


handler404 = 'accounts.views.page_not_found_view'

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("add/", views.add_post, name="add_post"),
    path('delete/<int:post_id>/', views.delete_post, name="delete_post"),
    path('like/<post_id>/', views.like_toggle),
    path('comment/add/', views.add_comment),
    ]

posts/models.py
from django.db import models
from accounts.models import UserAccounts
from django.db.models.signals import post_delete

from django.contrib.auth import get_user_model
from django.dispatch import receiver

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    caption = models.TextField()
    image = models.ImageField(upload_to="posts")
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def liked_users(self):
        objects = Like.objects.filter(post=self).values_list('user', flat=True)
        return objects


@receiver(post_delete, sender=Post)
def delete_post_image(sender, instance, *args, **kwargs):
    instance.image.delete(False)


class Like(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="user_likes")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_likes")

    class Meta:
        unique_together = ["user", "post"]


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name="user_comments")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="post_comments")
    comment = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


class HashTag(models.Model):
    tag = models.CharField(max_length=40)
    post = models.ManyToManyField(Post)

posts/forms.py
from django import forms
from .models import Post

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image','caption']

posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseNotFound
from django.shortcuts import HttpResponse, redirect, render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from .forms import PostAddForm
from .models import Comment, Like, Post

# Create your views here.


@login_required
def home_view(request):
    posts = Post.objects.all().prefetch_related("post_likes", 'post_comments', 'post_comments__user').select_related("user")
    likes = Like.objects.filter(post__in=posts, user=request.user).values_list("post", flat=True)

    def is_liked_add(p):
        p.is_liked = p.id in likes
        return p

    posts = list(map(is_liked_add, posts))
    return render(request, "posts/home.html", {"posts": posts})


@login_required
def add_post(request):
    if request.method == "POST":
        form = PostAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.success(request, "successful")
            return redirect("posts:home")
        else:
            return render(request, "posts/add_post.html", {"form": form})
    else:

        form = PostAddForm()
        return render(request, "posts/add_post.html", {"form": form})


@login_required
def like_toggle(request, post_id):
    post = get_object_or_404(Post, id = post_id)
    user = request.user
    response = {}
    try:
        already_liked = Like.objects.get(post=post, user=user)
        already_liked.delete()
        response['status'] = 'dislike'
    except Like.DoesNotExist:
        Like.objects.create(post=post, user=user)
        response['status'] = 'like'

    response['count'] = Like.objects.filter(post=post).count()

    return JsonResponse(response)


@login_required
@csrf_exempt
def add_comment(request):
    post_id = request.POST.get('post_id')
    comment = request.POST.get('comment')

    post = get_object_or_404(Post, id = post_id)
    user = request.user

    Comment.objects.create(user=user, post=post, comment=comment)
    return JsonResponse({'user':user.first_name, 'comment':comment})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id = post_id)
    if request.user == post.user:
        post.delete()
        next = request.GET.get('next', '/')
        return redirect(next)
    else:
        return HttpResponseNotFound()

templates/posts/add_post.html
{% extends 'posts/base.html' %}

{% load static %}
{% load widget_tweaks %}

{% block scripts_extra %}
    <script src="{% static 'posts/compressor.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.9/cropper.min.css">
{% endblock scripts_extra %}


{% block content %}
<div class="d-flex justify-content-center mt-0 mt-sm-20">
    <div class="w-full"
        style="max-width: 610px;">

        <!-- card -->
        <div class="bg-white border border-1 rounded mb-sm-20 p-10 p-sm-15">
            
            <h6 class="font-weight-semi-bold">New Post</i></h6>

            <form id="id_form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- preview target element -->
                <img id="target" class="w-full border rounded" src="" alt="">

                <div class="mb-10 d-flex justify-content-between">
                    <label class="btn text-muted font-weight-medium" for="id_image">Choose Image</label>
                    {% render_field form.image class="form-control d-none" placeholder=form.image.label %}
                    

                    <div style="display: none;" id="edit_menu">
                        <button id="free_crop" type="button" class="ico text-dark pl-0 border-0 bg-transparent font-size-16 font-weight-medium">FREE</button>
                        <button id="one_one_crop" type="button" class="ico text-dark border-0 bg-transparent font-size-16 font-weight-medium">1:1</i></button>
                        <button id="four_three_crop" type="button" class="ico text-dark border-0 bg-transparent font-size-16 font-weight-medium">4:3</i></button>
                        <button id="save_crop" type="button" class="btn btn-sm btn-square btn-primary rounded-circle"><i class="fas fa-check"></i></button>
                    </div>

                </div>

                <div id="caption_con">
                    <div class="mb-10">
                        {% render_field form.caption class="form-control" placeholder='Write a caption...' %}
                        <ul class="errorlist">
                            {% for err in form.caption.errors %}
                            <li>{{ err }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Post">
                </div>

            </form>

        </div>
        
    </div>

    <!-- right-side-bar -->
    <div class="d-none d-lg-block position-relative" style="max-width: 290px;width: 290px; margin-left: 40px;z-index: 1;">
        <div class="position-fixed" style="width: inherit;margin-top: 2em;">
            <!-- userpic & name -->
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                    <img class="border rounded-circle w-50 mr-10" src="{% static 'accounts/avatar.png' %}" alt="">
                    <div>
                        <div class="text-black font-weight-medium">designs.ui</div>
                        <div class="text-gray">ui/ux designs</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">More</button>
            </div>

            <!-- suggestion -->
            <div class="d-flex justify-content-between align-items-center  mt-20 mb-15">
                <div class="text-muted font-size-14 font-weight-medium">
                    Suggestions For You
                </div>
                <button class="ico text-dark border-0 bg-transparent font-size-12 font-weight-medium">See All</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10" src="https://images.unsplash.com/photo-1564048843342-6588968397ce?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80" alt="">
                    <div>
                        <div class="text-black font-weight-medium">picstay_kerala</div>
                        <div class="text-gray font-size-12">Suggested for you</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10" src="https://images.unsplash.com/photo-1574579991264-a87099cc17b1?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=40&q=80" alt="">
                    <div>
                        <div class="text-black font-weight-medium">amazingdestination.z</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

            <div class="d-flex justify-content-between align-items-center mb-10">
                <div class="d-flex align-items-center">
                    <img style="width: 35px; height: 35px; object-fit: cover;" class="border rounded-circle mr-10" src="https://images.unsplash.com/photo-1485206412256-701ccc5b93ca?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=42&q=80" alt="">
                    <div>
                        <div class="text-black font-weight-medium">jacobelordi</div>
                        <div class="text-gray font-size-12">Popular</div>
                    </div>
                </div>
                <button class="ico text-primary border-0 bg-transparent font-size-12 font-weight-medium">Follow</button>
            </div>

        </div>
    </div>

    <style>
        .cropper-view-box {
            outline: 1px solid #fff;
            outline-color: rgb(255 255 255 / 75%);
        }

        .cropper-face {
            background-color: transparent;
        }

        .cropper-line {
            background-color: #f3f5f7;
        }

        .cropper-point {
            background-color: #fff;
        }

        .cropper-modal {
            background-color: #fff;
        }
    </style>

    <script>
        var form = document.getElementById('id_form')
        var imgSelector = document.getElementById('id_image')
        var imgTarget = document.querySelector('#target')
        var editMenu = document.querySelector('#edit_menu')
        var freeCrop = document.querySelector('#free_crop')
        var oneOneCrop = document.querySelector('#one_one_crop')
        var fourThreeCrop = document.querySelector('#four_three_crop')
        var saveCrop = document.querySelector('#save_crop')
        var captionCon = document.querySelector('#caption_con')
        
        

        var cropper;
        var blob;

        // previews image when selected from storage
        function readURL(event) {
            
            let input = event.target
            if (input.files && input.files[0]) {

                var reader = new FileReader();

                reader.onload = function (e) {

                    // setting input file to img source
                    imgTarget.setAttribute('src', e.target.result);
                    document.querySelector('label[for="id_image"]').innerHTML = 'Change Image'
                    

                    // destroying cropper if already created
                    // to prevent problems when changing image 
                    if(cropper != undefined){
                        cropper.destroy()
                        cropper = undefined;
                    }

                    // initializer cropping instance
                    cropper =  new Cropper(imgTarget, {
                        aspectRatio: NaN,
                        viewMode: 1,
                        background: false,
                        zoomable: false,
                        zoomOnTouch: false,
                        zoomOnWheel: true,
                        ready: function(){
                            editMenu.style.display = "block";
                            captionCon.style.display = "none"
                            cropper.setCropBoxData(cropper.getCanvasData())
                        }
                    })
                }

                // reading image from file input and setting to file reader
                reader.readAsDataURL(input.files[0]);
            }
        }

        imgSelector.addEventListener('change', readURL)

        // applying crop and previews new image
        saveCrop.addEventListener('click', function(){

            // return cropped image as blob
            cropper.getCroppedCanvas().toBlob((blb) => {
                blob = blb
                cropper.destroy()
                var reader = new FileReader();

                reader.onload = function (e) {
                    imgTarget.setAttribute('src', e.target.result);
                }

                // setting cropped result as new preview
                reader.readAsDataURL(blob);


                editMenu.style.display = "none";
                captionCon.style.display = "block"


            })
        })

        // compressing image on form submission
        form.addEventListener('submit', function(event){
            event.preventDefault();

            if(blob != undefined){

                var file = new File([blob], imgSelector.files[0].name, {type: blob.type, lastModified: new Date().getTime()})
                console.log(file.size)

                // compression start here
                new Compressor(file, {
                quality: 0.3,
                width: 480,
                maxWidth: 480,
                success(result) {
                    var formData = new FormData()
                    formData.append('csrfmiddlewaretoken', form.csrfmiddlewaretoken.value)
                    formData.append('caption', form.caption.value)

                    // The third parameter is required for server
                    formData.append('image', result, result.name);

                    // submititing form as ajax post
                    $.ajax("{% url 'posts:add_post' %}", {
                        method: 'POST',
                        data: formData,
                        processData: false,
                        contentType: false,
                        success() {
                            console.log('Upload success');
                            location.replace('{% url "posts:home" %}')
                        },
                        error() {
                            console.log('Upload error');
                        },
                    });

                    }
                })
            }


        })

        // crop tools methods
        freeCrop.addEventListener('click', () => cropper.setAspectRatio(NaN) )
        oneOneCrop.addEventListener('click', () => cropper.setAspectRatio(1/1) )
        fourThreeCrop.addEventListener('click', () => cropper.setAspectRatio(4/3) )
        

    </script>

</div>
{% endblock content %}

templates/posts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            Instagram
        {% endblock title %}
            
    </title>
    <link href="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/css/halfmoon-variables.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/halfmoon@1.1.1/js/halfmoon.min.js"></script>

    <script
    src="https://code.jquery.com/jquery-3.5.1.min.js"
    integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
    crossorigin="anonymous"></script>
    
    {% block scripts_extra %}
        
    {% endblock scripts_extra %}
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="{% static 'posts/style.css' %}">
    <link rel="shortcut icon" href="{% static 'accounts/favicon.ico' %}" />
    
</head>
<body>
    <!-- Navbar with a navbar-item as dropdown -->
    <div class="nav p-5 border-bottom 
    border-1 w-full d-flex justify-content-center
    position-fixed bg-white" style="z-index: 999;">
        <nav class="navbar border-0" style="width: 950px;">
            <!-- Navbar brand -->
            <a href="{% url 'posts:home' %}" class="navbar-brand">
            <img class="w-100 h-auto mt-10" src="{% static 'accounts/logo-text.png' %}" alt="...">
            </a>

            <!-- Inline form with input group -->
            <form class="form-inline ml-auto d-none d-sm-inline" action="..." method="..."> <!-- ml-auto = margin-left: auto -->
                <div class="input-group">
                <input type="text" class="form-control form-control-sm" placeholder="Search" required="required">
                
                </div>
            </form>

            <!-- Navbar nav -->
            <ul class="navbar-nav ml-auto"> <!-- ml-auto = margin-left: auto -->
            <li class="nav-item">
                <a href="{% url 'posts:home' %}" class="nav-link font-size-22 d-none d-sm-flex"><i class="fas fa-home"></i></a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link font-size-20"><i class="far fa-paper-plane"></i></a>
            </li>
            <li class="nav-item">
                <a href="#" class="nav-link font-size-22"><i class="far fa-heart"></i></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" id="nav-link-dropdown-toggle">
                <img class="rounded-circle w-25 border border-1" src="{% static 'accounts/avatar.png' %}" alt="">
                <i class="fa fa-angle-down ml-5" aria-hidden="true"></i> <!-- ml-5= margin-left: 0.5rem (5px) -->
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="nav-link-dropdown-toggle">
                <a href="{% url 'posts:add_post' %}" class="dropdown-item"><i class="far fa-plus-square p-5 w-25 mr-5 font-size-16"></i>New Post</a>
                <a href="#" class="dropdown-item"><i class="far fa-user-circle p-5 w-25 mr-5 font-size-16"></i>Profile</a>
                <a href="#" class="dropdown-item"><i class="fas fa-cog p-5 w-25 mr-5 font-size-16"></i>Settings</a>
                <a href="#" class="dropdown-item"><i class="far fa-bookmark p-5 w-25 mr-5 font-size-16"></i>Saved</a>


                <div class="dropdown-divider"></div>
                <a href="{% url 'accounts:logout' %}" class="dropdown-item">Log Out</a>
                </div>
            </li>
            </ul>
        </nav>
    </div>
    <div class="w-full d-flex justify-content-center" style="background-color: #fafafa;">
        <div class="" style="width: 950px;margin-top: 60px;">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    {% if messages %}
    <div style="width:300px;position: fixed;bottom: 10px; right: 10px;">
        {% for msg in messages %}
            <div class="alert mb-5" role="alert">
                <button class="close" data-dismiss="alert" type="button" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="alert-heading">{{ msg }}</h4>
            </div>
        {% endfor %}
    </div>
    {% endif %}
    <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.1/dist/lazyload.min.js"></script>
    <script>
        var lazyLoadInstance = new LazyLoad({
        // Your custom settings go here
        });
    </script>

</body>
</html>